# Generated by Django 4.0.3 on 2022-03-04 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.CharField(max_length=10000000)),
                ('room', models.CharField(max_length=10000000)),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='value',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
